/**
 * Premium Text Effects Catalog
 *
 * 20 highly stylized preset text effects inspired by premium design aesthetics.
 * Each effect contains standard typography settings compatible with Clypra's text renderer.
 *
 * Note: All effects are fully free.
 */

export interface TextEffectPreset {
  id: string;
  name: string;
  category: "Classic" | "Hits" | "Animation" | "Food" | "Textile Art" | "Manuscript" | "Metal" | "Neon" | "3D" | "Gradient" | "Glitch" | "Retro" | "Clean" | "Organic";
  fontFamily: string;
  color: string; // supports solid hex or comma-separated vertical gradients
  fontWeight: "normal" | "bold" | number;
  fontStyle: "normal" | "italic";
  stroke?: {
    color: string;
    width: number;
  };
  shadow?: {
    color: string;
    blur: number;
    offsetX: number;
    offsetY: number;
  };
  background?: {
    color: string;
    padding: number;
    borderRadius: number;
  };
  premium?: boolean;
}

export const TEXT_EFFECTS: TextEffectPreset[] = [
  {
    id: "glow-yellow",
    name: "Yellow Glow",
    category: "Neon",
    fontFamily: "Outfit",
    color: "#ffffff",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#000000", width: 6 },
    shadow: { color: "#ffff00", blur: 18, offsetX: 0, offsetY: 0 },
  },
  {
    id: "neon-red",
    name: "Red Neon",
    category: "Neon",
    fontFamily: "Outfit",
    color: "#ffffff",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#ff1e1e", width: 6 },
    shadow: { color: "#ff1e1e", blur: 18, offsetX: 0, offsetY: 0 },
  },
  {
    id: "classic-gold",
    name: "Classic Gold",
    category: "Classic",
    fontFamily: "Outfit",
    color: "#ffe066, #b38600",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#4d3300", width: 4 },
    shadow: { color: "rgba(0, 0, 0, 0.6)", blur: 10, offsetX: 3, offsetY: 5 },
  },
  {
    id: "retro-sunset",
    name: "Retro Sunset",
    category: "Gradient",
    fontFamily: "Poppins",
    color: "#ff3e00, #ff0077, #aa00ff",
    fontWeight: "bold",
    fontStyle: "italic",
    stroke: { color: "#000000", width: 3 },
    shadow: { color: "#000000", blur: 0, offsetX: 6, offsetY: 6 },
  },
  {
    id: "bubblegum-pink",
    name: "Bubblegum Pink",
    category: "Hits",
    fontFamily: "Poppins",
    color: "#ffffff",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#ff66cc", width: 8 },
    shadow: { color: "#ff0099", blur: 4, offsetX: 0, offsetY: 4 },
  },
  {
    id: "3d-wood",
    name: "3D Wood",
    category: "Classic",
    fontFamily: "Roboto",
    color: "#d2b48c, #8b5a2b",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#3d2314", width: 5 },
    shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 4, offsetY: 4 },
  },
  {
    id: "cyber-neon",
    name: "Cyber Neon",
    category: "Neon",
    fontFamily: "Outfit",
    color: "#00ffff",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#ff00ff", width: 5 },
    shadow: { color: "#ff00ff", blur: 15, offsetX: 0, offsetY: 0 },
  },
  {
    id: "midnight-glow",
    name: "Midnight Glow",
    category: "Hits",
    fontFamily: "Inter",
    color: "#120a2a",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#00ffcc", width: 4 },
    shadow: { color: "#00ffcc", blur: 12, offsetX: 0, offsetY: 0 },
  },
  {
    id: "glitch-tech",
    name: "Glitch Tech",
    category: "Glitch",
    fontFamily: "Outfit",
    color: "#ffffff",
    fontWeight: 700,
    fontStyle: "normal",
    stroke: { color: "#0f0f14", width: 4 },
    shadow: { color: "#ff0055", blur: 8, offsetX: -4, offsetY: 0 },
  },
  {
    id: "comic-book",
    name: "Comic Book",
    category: "Hits",
    fontFamily: "Poppins",
    color: "#ffd700",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#000000", width: 8 },
    shadow: { color: "#000000", blur: 0, offsetX: 6, offsetY: 0 },
  },
  {
    id: "graffiti-splash",
    name: "Graffiti Splash",
    category: "Textile Art",
    fontFamily: "Outfit",
    color: "#39ff14",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#000000", width: 6 },
    background: { color: "rgba(0,0,0,0.8)", padding: 12, borderRadius: 8 },
  },
  {
    id: "silver-chrome",
    name: "Silver Chrome",
    category: "Metal",
    fontFamily: "Outfit",
    color: "#ffffff, #999999, #eeeeee",
    fontWeight: "bold",
    fontStyle: "italic",
    stroke: { color: "#444444", width: 3 },
    shadow: { color: "rgba(255,255,255,0.4)", blur: 8, offsetX: 0, offsetY: 0 },
  },
  {
    id: "frozen-ice",
    name: "Frozen Ice",
    category: "Food",
    fontFamily: "Outfit",
    color: "#e6ffff, #80e5ff",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#0088cc", width: 4 },
    shadow: { color: "#e6ffff", blur: 10, offsetX: 0, offsetY: 0 },
  },
  {
    id: "fire-flame",
    name: "Fire Flame",
    category: "Animation",
    fontFamily: "Poppins",
    color: "#ffff00, #ff3300",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#660000", width: 5 },
    shadow: { color: "#ff6600", blur: 15, offsetX: 0, offsetY: -2 },
  },
  {
    id: "candy-rainbow",
    name: "Candy Rainbow",
    category: "Hits",
    fontFamily: "Poppins",
    color: "#ff007f, #aa00ff, #00c8ff, #00ff66",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#111111", width: 4 },
    shadow: { color: "rgba(0,0,0,0.3)", blur: 4, offsetX: 2, offsetY: 2 },
  },
  {
    id: "vintage-newspaper",
    name: "Vintage Newspaper",
    category: "Manuscript",
    fontFamily: "Roboto",
    color: "#111111",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#f5f5dc", width: 2 },
    shadow: { color: "rgba(0,0,0,0.15)", blur: 5, offsetX: 3, offsetY: 3 },
  },
  {
    id: "acid-lime",
    name: "Acid Lime",
    category: "Neon",
    fontFamily: "Outfit",
    color: "#dfff11",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#0a0c00", width: 7 },
    shadow: { color: "#0a0c00", blur: 0, offsetX: 4, offsetY: 4 },
  },
  {
    id: "electric-blue",
    name: "Electric Blue",
    category: "Neon",
    fontFamily: "Outfit",
    color: "#00dfff",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#0033cc", width: 6 },
    shadow: { color: "#00dfff", blur: 14, offsetX: 0, offsetY: 0 },
  },
  {
    id: "barbie-dream",
    name: "Barbie Dream",
    category: "Gradient",
    fontFamily: "Poppins",
    color: "#ff99cc, #ff007f",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#ffffff", width: 5 },
    shadow: { color: "#ff007f", blur: 10, offsetX: 0, offsetY: 0 },
  },
  {
    id: "royal-emerald",
    name: "Royal Emerald",
    category: "Classic",
    fontFamily: "Roboto",
    color: "#006633, #00cc66",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#d4af37", width: 3 },
    shadow: { color: "rgba(0,0,0,0.5)", blur: 8, offsetX: 2, offsetY: 4 },
  },
  {
    id: "carbon-tech",
    name: "Carbon Tech",
    category: "Metal",
    fontFamily: "Inter",
    color: "#333333",
    fontWeight: "bold",
    fontStyle: "normal",
    stroke: { color: "#ff3300", width: 3 },
    background: { color: "#111111", padding: 10, borderRadius: 4 },
  },
  {
    id: "molten-gold-3d",
    name: "Molten Gold 3D",
    category: "Metal",
    fontFamily: "Impact",
    color: "#F5C518",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#4A2800", width: 2 },
    shadow: { color: "#1A0900", blur: 12, offsetX: 5, offsetY: 6 },
  },
  {
    id: "neon-crimson",
    name: "Neon Crimson",
    category: "Neon",
    fontFamily: "Impact",
    color: "#FFFFFF",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#CC0000", width: 4 },
    shadow: { color: "#FF0000", blur: 20, offsetX: 0, offsetY: 0 },
  },
  {
    id: "electric-rainbow",
    name: "Electric Rainbow",
    category: "Gradient",
    fontFamily: "Impact",
    color: "#FF0000",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#FFFFFF", width: 4 },
    shadow: { color: "#000000", blur: 8, offsetX: 3, offsetY: 4 },
  },
  {
    id: "obsidian-chrome",
    name: "Obsidian Chrome",
    category: "Metal",
    fontFamily: "Impact",
    color: "#2A2A2A",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#FFFFFF", width: 1 },
    shadow: { color: "#000000", blur: 20, offsetX: 0, offsetY: 8 },
  },
  {
    id: "lava-forge",
    name: "Lava Forge",
    category: "3D",
    fontFamily: "Impact",
    color: "#FF4500",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#3D0000", width: 3 },
    shadow: { color: "#FF4500", blur: 30, offsetX: 0, offsetY: 0 },
  },
  {
    id: "arctic-glass",
    name: "Arctic Glass",
    category: "Classic",
    fontFamily: "Impact",
    color: "#A8D8EA",
    fontWeight: 700,
    fontStyle: "normal",
    stroke: { color: "#FFFFFF", width: 1.5 },
    shadow: { color: "#00BFFF", blur: 25, offsetX: 0, offsetY: 0 },
  },
  {
    id: "graffiti-bomb",
    name: "Graffiti Bomb",
    category: "Textile Art",
    fontFamily: "Impact",
    color: "#FFA500",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#000000", width: 8 },
    shadow: { color: "#000000", blur: 0, offsetX: 5, offsetY: 5 },
  },
  {
    id: "holographic-foil",
    name: "Holographic Foil",
    category: "Gradient",
    fontFamily: "Impact",
    color: "#C44DFF",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#FFFFFF", width: 1 },
  },
  {
    id: "retro-varsity",
    name: "Retro Varsity",
    category: "Classic",
    fontFamily: "Impact",
    color: "#003087",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#FFD700", width: 8 },
    shadow: { color: "#000000", blur: 6, offsetX: 4, offsetY: 4 },
  },
  {
    id: "synthwave-double-neon",
    name: "Synthwave Neon",
    category: "Neon",
    fontFamily: "Impact",
    color: "#FF10F0",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#FFFFFF", width: 2 },
    shadow: { color: "#FF10F0", blur: 25, offsetX: 0, offsetY: 0 },
  },
  {
    id: "bone-carved",
    name: "Bone Carved",
    category: "3D",
    fontFamily: "Georgia",
    color: "#F0E8D0",
    fontWeight: 700,
    fontStyle: "normal",
    stroke: { color: "#D4C4A8", width: 1 },
    shadow: { color: "#3D2B1F", blur: 10, offsetX: 4, offsetY: 5 },
  },
  {
    id: "toxic-slime",
    name: "Toxic Slime",
    category: "Gradient",
    fontFamily: "Impact",
    color: "#39FF14",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#003300", width: 3 },
    shadow: { color: "#39FF14", blur: 30, offsetX: 0, offsetY: 0 },
  },
  {
    id: "studio-broadcast",
    name: "Studio Broadcast",
    category: "Classic",
    fontFamily: "Arial",
    color: "#FFFFFF",
    fontWeight: 700,
    fontStyle: "normal",
    shadow: { color: "#000000", blur: 25, offsetX: 0, offsetY: 6 },
  },
  {
    id: "galactic-nebula",
    name: "Galactic Nebula",
    category: "Hits",
    fontFamily: "Impact",
    color: "#9B59B6",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#FFFFFF", width: 1 },
    shadow: { color: "#9B59B6", blur: 40, offsetX: 0, offsetY: 0 },
  },
  {
    id: "glitch-corrupt",
    name: "Glitch Corrupt",
    category: "Glitch",
    fontFamily: "Impact",
    color: "#FFFFFF",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#00FFFF", width: 1 },
  },
  {
    id: "ref-gold-3d-premium",
    name: "Gold 3D Premium",
    category: "3D",
    fontFamily: "Impact",
    color: "#FFE87C, #F5B018, #C87000, #914500, #FFE87C",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#1D0D00", width: 2 },
    shadow: { color: "#D47000", blur: 45, offsetX: 0, offsetY: 0 },
    premium: true,
  },
  {
    id: "ref-red-neon-outline",
    name: "Red Neon Outline",
    category: "Neon",
    fontFamily: "Impact",
    color: "#FFFFFF",
    fontWeight: 900,
    fontStyle: "normal",
    stroke: { color: "#FF0000", width: 5 },
    shadow: { color: "#FF0000", blur: 10, offsetX: 0, offsetY: 0 },
    premium: true,
  },
  {
    id: "newspaper-offset",
    name: "Newspaper Offset",
    category: "Retro",
    fontFamily: "Playfair Display",
    color: "#000000",
    fontWeight: 700,
    fontStyle: "italic",
    premium: true,
  },
  {
    id: "frosted-glass-etch",
    name: "Frosted Glass Etch",
    category: "Clean",
    fontFamily: "Cinzel",
    color: "rgba(235, 247, 250, 0.35)",
    fontWeight: 300,
    fontStyle: "normal",
    shadow: { color: "#000000", blur: 2, offsetX: 1.5, offsetY: 1.5 },
    premium: true,
  },
  {
    id: "burned-wood-pyrography",
    name: "Burned Wood Pyrography",
    category: "Organic",
    fontFamily: "Cinzel Decorative",
    color: "#060302",
    fontWeight: 900,
    fontStyle: "normal",
    shadow: { color: "rgba(6, 3, 2, 0.98)", blur: 3, offsetX: 0, offsetY: 0 },
    premium: true,
  },
  {
    id: "victorian-ornate",
    name: "Victorian Ornate",
    category: "Retro",
    fontFamily: "Cinzel Decorative",
    color: "#2d1802, #d4af37, #aa7c11, #f9e8a2, #8c6227, #f3e5ab, #422a08",
    fontWeight: 700,
    fontStyle: "normal",
    stroke: { color: "#ffffff", width: 0.5 },
    shadow: { color: "#150e04", blur: 0, offsetX: 7.5, offsetY: 7.5 },
    premium: true,
  },
  {
    id: "calligraphy-ink",
    name: "Calligraphy Ink",
    category: "Clean",
    fontFamily: "Pinyon Script",
    color: "#02050f",
    fontWeight: 400,
    fontStyle: "italic",
    shadow: { color: "#02050f", blur: 1.8, offsetX: 0, offsetY: 0 },
    premium: true,
  },
];
